import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/providers/session-provider";
import { BackToTop } from "@/components/ui/back-to-top";
import { FloatingMenu } from "@/components/landing";
import { NoSSR } from "@/components/ui/no-ssr";
import { Toaster } from "@/components/ui/sonner";
import { Chatbox } from "@/components/ui/chatbox";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <AuthProvider>
          {children}
          <NoSSR>
            <BackToTop />
            <FloatingMenu />
            <Chatbox dailyLimit={50} />
          </NoSSR>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
