export { Header } from "./header";
export { Footer } from "./footer";
export { Hero } from "./hero";
export { Features } from "./features";
export { Services } from "./services";
export { Products } from "./products";
export { Testimonials } from "./testimonials";
export { CTA } from "./cta";
export { FloatingMenu } from "./floating-menu";
